confirmModulesPurge: false

allowBuilds:
  '@firebase/util': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - esbuild
  - '@firebase/util'
  - protobufjs
  - unrs-resolver

overrides:
  'ajv@>=8': 8.18.0
  'eslint>ajv': 6.12.6
  fast-xml-parser: 5.5.7
  lodash: 4.18.1
  'minimatch@>=5 <5.1.7': 5.1.9
  'minimatch@>=9 <9.0.6': 9.0.9
  'minimatch@>=10 <10.2.1': 10.2.5
  node-forge: 1.4.0
  'picomatch@<2.3.2': 2.3.2
  'picomatch@>=4 <4.0.4': 4.0.4
  serialize-javascript: 7.0.5
