-- Generated by backfill-users-to-d1.mjs. Idempotent; safe to re-run.
-- Order: users (rich + FK stubs) -> contacts -> conversation_id links -> email_hash.

-- users: rich rows
INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('049Wk4gbcuZJJ9MbCeN7GQuRYer2', 'gogo', NULL, 'gogo_gogo', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('2IFc56527UOATct95FnfnyO1DOb2', NULL, NULL, 'local_test_3', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('9dsRDwoLA2eTCQkLDCywhqqVKxl1', 'Davíð Roach Gunnarsson', 'https://lh3.googleusercontent.com/a/ACg8ocJ0vqRsp2Sn2zZyW_ZuzYAXIesJ1w8huafgF5hVR_ohNk9tzQ=s96-c', 'david_roach_gunnarss', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('Avpry5LR0gebuh3tV1lQsGovYLl1', 'Hyo-sam Nandkisore', 'https://lh3.googleusercontent.com/a/ACg8ocISt6CKnFyzeo4XP_-pTojd16GZWVCvbz340AgwI_knp9wSMw=s96-c', 'hyo_sam_nandkisore', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('Cn5pDX2eyPSmktBdyYGZIy6v1uF2', 'kalli', NULL, 'kalli_kalli', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('FXw3enl76NfhWTVliaW4lojwDam1', 'Gunnar Roach', 'https://lh3.googleusercontent.com/a/ACg8ocI-pFCbDOgX8sa0DOmGSeh9RywDJcfX3Hlq8Vqy4vCbBcXP0g=s96-c', 'gunnar_roach', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2', 'test_username_1', NULL, 'test_username_1', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('JzeKl0JyECePK1CDKOzFIdMEC2i1', 'Hafrún Kolbeinsdóttir', 'https://lh3.googleusercontent.com/a/ACg8ocLdHmDNg4fFuBTUiqXpUQKsLY7fa63aeO4Bguq5SjrvKVMpmLM=s96-c', 'hafrun_kolbeinsdotti', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('KYM8gzxMu6MJvPkJaTC0hFh2cn52', 'Jázmin Bárdos', 'https://lh3.googleusercontent.com/a/ACg8ocKBGQOUZxV939AuqfY-UFRU2J1LjLwz7_O2H5s3KVrgI_ZXm04=s96-c', 'jazmin_bardos', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('L0FDWn6KYHWmDqu8dyy1aLwvPHZ2', 'Smári R Gunnarsson', 'https://lh3.googleusercontent.com/a/ACg8ocJnNJNIBHB-FccXc3KbL3gVk6HhTr6c7C8qbafswAOGUxQ5Ww=s96-c', 'smari_r_gunnarsson', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('QKhccP7EjZOX3LHl6jXKxqyXK0m2', 'jonni_jonni', NULL, 'jonni_jonni', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('RVrF9x2WFbQfGcrfzBYhG0td7h22', 'Þóra Andrésdóttir', 'https://lh3.googleusercontent.com/a/ACg8ocKwM7AhRJIHcJymS2Q0TRrHSmOQyO12EJxDIAWfPFBMoIb0Yw=s96-c', 'thora_andresdottir', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('RZs9qkTS8ebgV14v7cLdMOcOOyi2', 'Hildur Sif Hilmarsdóttir', 'https://lh3.googleusercontent.com/a/ACg8ocI_sFio2I_T3nvL_ifyfUzcl6ViRwNlEuIDJ1MkddNhqUC47pjh=s96-c', 'hildur_sif_hilmarsdo', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('UUAkuLxFHDfIgi8Ne7ziP0buCQU2', 'Þorbjörg Roach Gunnarsdóttir', 'https://lh3.googleusercontent.com/a/ACg8ocJmBMgUhjsaAoPeqYTkp5gofiEf0YJRfy1EtwSMTzB_acYQeQ=s96-c', 'thorbjorg_roach_gunn', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('UlJLeEdIiUYtt79qDbHRmpWszkd2', 'livanuj', NULL, 'livanuj', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('VCREsDNSvRcxQWKmHHkTNk9VcOu1', 'Töggur Roach', 'https://lh3.googleusercontent.com/a/ACg8ocLmEPjkQWD1b63tJVTWIwuxX4YtS0PF7f9zBKRVBfb1eO5TLR8=s96-c', 'toggur_roach', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('VtaPJJRr8nYkO0dcA2Op4UckE9F2', 'MC Bjór', 'https://lh3.googleusercontent.com/a/ACg8ocIqk2yHuE0uU8OXWFo44sv0G9GGz4qvXIDN4nrHt3XiVLG82zIp=s96-c', 'mc_bjor', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('XxlRUx60m3Na3lF7qKsvuPDrqBH2', NULL, NULL, 'local_test', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('dhJpbVtgazfdRuw89be3gmZ5y1I2', 'Robert K.', 'https://lh3.googleusercontent.com/a/ACg8ocLQIDk8DUKErBO9Itf5_0JMfoguQVk2cAh3L_yLFi1rtRR81RXc=s96-c', 'robert_k', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', 'https://lh3.googleusercontent.com/a/ACg8ocJtBoO3wOewLIpAFfn7si5VeQAV2DITAl6iunWpHgfUw6dIWQ=s96-c', 'kristinn_roach_gunna', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('j0UhlxrSgVeWSIgNVsvrs6LgNP02', 'Vladka Gondza', 'https://lh3.googleusercontent.com/a/ACg8ocIunB5cu9eZa7H3ANfed6x-bIZr2pg7AK83zGemIqzCcsUYDQ=s96-c', 'vladka_gondza', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('mkc4IiI5LhSQH64gt1OvoncTYrt2', 'Gudmundur', 'https://lh3.googleusercontent.com/a/ACg8ocJNfzIF03fJy_2hUysBfMshgSAj1kNO4ASG5An4GXuJlQvt1w=s96-c', 'gudmundur', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('nS4dmOOpWBNKNInxpbK4DmupjjA3', 'Bergur Thorgeirsson', 'https://lh3.googleusercontent.com/a/ACg8ocKDmv4u2NtL0iOn6AFoyCe2E2F9KisBO9B2VSfPuLyYxxPbxg=s96-c', 'bergur_thorgeirsson', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('ngB04ba21zbBpuwrbf3JbnmZ0Gr2', 'kiddi', NULL, 'kiddi', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('o5ATY42g56N6pufEJRQ6UPy0Joy1', 'Páll Pampichler Pálsson', 'https://lh3.googleusercontent.com/a/ACg8ocIOiNLevS2rKG_WiYiYxaIoQg5TblrlsBjbo55SYv-u9qASbA=s96-c', 'pall_pampichler_pals', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('paZMw9G5RMdeClPCMGYrvMScIZk1', 'Aron Sigurgeirsson', 'https://lh3.googleusercontent.com/a/ACg8ocIWkDpVesO4lIP1aZFPwJh-uYXzA__LBjk45kCX_yOGN_7xxw=s96-c', 'aron_sigurgeirsson', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('rC8YIKPrpGOkHjMrUJVlaKqcHSk1', 'Benjen Mormont', 'https://lh3.googleusercontent.com/a/ACg8ocJGXhhrLD4WhyGoKsLoinPE6y-1SXnIIZdH1Bix9pNpyPBB-g=s96-c', 'benjen_mormont', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('rXEVXKdjn8gvDS2nHCi4ly7aZUq2', NULL, NULL, 'local_test_2', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('tE4U95xm0zYjlPuqdLQk2JAYGM63', 'Töggur Roach', 'https://lh3.googleusercontent.com/a/ACg8ocLmEPjkQWD1b63tJVTWIwuxX4YtS0PF7f9zBKRVBfb1eO5TLR8=s96-c', NULL, 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('tSwF1qWgcBdO4X1eTTofOWwIdWH2', 'test', NULL, 'test_test', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

INSERT INTO users (id, display_name, photo_url, username, created_at, registered_at)
VALUES ('wLFTAqKYsocZHS3BIhd4PyblaEf1', 'test_username_2', NULL, 'test_username_2', 1782526001306, 1782526001306)
ON CONFLICT(id) DO UPDATE SET
  display_name  = COALESCE(users.display_name, excluded.display_name),
  photo_url     = COALESCE(users.photo_url, excluded.photo_url),
  username      = COALESCE(users.username, excluded.username),
  registered_at = COALESCE(users.registered_at, excluded.registered_at);

-- users: FK stubs for deleted / identity-less contact endpoints
INSERT OR IGNORE INTO users (id, display_name, created_at) VALUES ('09F1ryHgobTiwlfqF6Sf3ZdeMFp2', NULL, 1782526001306);

INSERT OR IGNORE INTO users (id, display_name, created_at) VALUES ('8cqRApeZElMTXpGVTlZcOMq8Nfj1', NULL, 1782526001306);

INSERT OR IGNORE INTO users (id, display_name, created_at) VALUES ('FKLnfsnu2mdlb0yyGF5UJ5tisas2', NULL, 1782526001306);

INSERT OR IGNORE INTO users (id, display_name, created_at) VALUES ('UdPT5z43AoNeIYuerj1yLu5HrQf2', NULL, 1782526001306);

INSERT OR IGNORE INTO users (id, display_name, created_at) VALUES ('we3njw1bnSNKs01j7g64NR90F7j2', NULL, 1782526001306);

-- contacts
INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('049Wk4gbcuZJJ9MbCeN7GQuRYer2', 'VCREsDNSvRcxQWKmHHkTNk9VcOu1', 'Töggur Roach', NULL, 1782074971773, 1782074971773);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('049Wk4gbcuZJJ9MbCeN7GQuRYer2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1782074768934, 1782074768934);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('09F1ryHgobTiwlfqF6Sf3ZdeMFp2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'kiddi', NULL, 1768345767638, 1768345767638);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('8cqRApeZElMTXpGVTlZcOMq8Nfj1', 'iTAqv24EaybY6DB5DKG32zp5my42', '', NULL, 1782526001306, 1782526001306);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('9dsRDwoLA2eTCQkLDCywhqqVKxl1', 'FXw3enl76NfhWTVliaW4lojwDam1', 'Gunnar Roach', NULL, 1775008263548, 1775008263548);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('9dsRDwoLA2eTCQkLDCywhqqVKxl1', 'RVrF9x2WFbQfGcrfzBYhG0td7h22', 'Þóra Andrésdóttir', NULL, 1774059118342, 1774059118342);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('9dsRDwoLA2eTCQkLDCywhqqVKxl1', 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2', 'Þorbjörg Roach Gunnarsdóttir', NULL, 1774059118345, 1774059118345);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('9dsRDwoLA2eTCQkLDCywhqqVKxl1', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1772865691780, 1778116712903);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('Avpry5LR0gebuh3tV1lQsGovYLl1', 'KYM8gzxMu6MJvPkJaTC0hFh2cn52', 'Jázmin Bárdos', NULL, 1774054711317, 1774054914829);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('Avpry5LR0gebuh3tV1lQsGovYLl1', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1771619135220, 1778899734952);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('Avpry5LR0gebuh3tV1lQsGovYLl1', 'mkc4IiI5LhSQH64gt1OvoncTYrt2', 'Gudmundur', NULL, 1774054711319, 1776685528854);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('Cn5pDX2eyPSmktBdyYGZIy6v1uF2', 'QKhccP7EjZOX3LHl6jXKxqyXK0m2', 'jonni_jonni', NULL, 1779740785498, 1779740830341);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('Cn5pDX2eyPSmktBdyYGZIy6v1uF2', 'VCREsDNSvRcxQWKmHHkTNk9VcOu1', 'Töggur Roach', NULL, 1781809442246, 1781809442246);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('Cn5pDX2eyPSmktBdyYGZIy6v1uF2', 'XxlRUx60m3Na3lF7qKsvuPDrqBH2', 'No Name', NULL, 1782407085091, 1782407085091);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('Cn5pDX2eyPSmktBdyYGZIy6v1uF2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1779744857940, 1779744857940);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('FKLnfsnu2mdlb0yyGF5UJ5tisas2', 'iTAqv24EaybY6DB5DKG32zp5my42', '', NULL, 1782526001306, 1782526001306);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('FXw3enl76NfhWTVliaW4lojwDam1', '9dsRDwoLA2eTCQkLDCywhqqVKxl1', 'Davíð Roach Gunnarsson', NULL, 1774452150439, 1777578299725);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('FXw3enl76NfhWTVliaW4lojwDam1', 'L0FDWn6KYHWmDqu8dyy1aLwvPHZ2', 'Smári R Gunnarsson', NULL, 1778349091503, 1778349142752);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('FXw3enl76NfhWTVliaW4lojwDam1', 'RVrF9x2WFbQfGcrfzBYhG0td7h22', 'Þóra Andrésdóttir', NULL, 1771875038113, 1778606155526);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('FXw3enl76NfhWTVliaW4lojwDam1', 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2', 'Þorbjörg Roach Gunnarsdóttir', NULL, 1774452146148, 1774452146148);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('FXw3enl76NfhWTVliaW4lojwDam1', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1770387223857, 1779207956783);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2', 'VCREsDNSvRcxQWKmHHkTNk9VcOu1', 'Töggur Roach', NULL, 1779569740560, 1779569740560);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2', 'wLFTAqKYsocZHS3BIhd4PyblaEf1', 'test_username_2', NULL, 1779569576220, 1779569620592);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('JzeKl0JyECePK1CDKOzFIdMEC2i1', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach', NULL, 1771721819005, 1778882582564);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('KYM8gzxMu6MJvPkJaTC0hFh2cn52', 'Avpry5LR0gebuh3tV1lQsGovYLl1', 'Hyo-sam Nandkisore', NULL, 1774054585580, 1774055155679);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('KYM8gzxMu6MJvPkJaTC0hFh2cn52', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kiddi.__.', NULL, 1772400030601, 1779986288404);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('L0FDWn6KYHWmDqu8dyy1aLwvPHZ2', 'FXw3enl76NfhWTVliaW4lojwDam1', 'Gunnar Roach', NULL, 1777962293529, 1777962293529);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('L0FDWn6KYHWmDqu8dyy1aLwvPHZ2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1779747692270, 1779908467255);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('QKhccP7EjZOX3LHl6jXKxqyXK0m2', 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2', 'kalli', NULL, 1779740785876, 1779741019016);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('RVrF9x2WFbQfGcrfzBYhG0td7h22', '9dsRDwoLA2eTCQkLDCywhqqVKxl1', 'Davíð Roach Gunnarsson', NULL, 1772972895926, 1778507381887);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('RVrF9x2WFbQfGcrfzBYhG0td7h22', 'FXw3enl76NfhWTVliaW4lojwDam1', 'Gunnar Roach', NULL, 1771506902846, 1772136476194);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('RVrF9x2WFbQfGcrfzBYhG0td7h22', 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2', 'Þorbjörg Roach Gunnarsdóttir', NULL, 1770226435071, 1770311942518);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('RVrF9x2WFbQfGcrfzBYhG0td7h22', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1771699260783, 1779731566422);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('RZs9qkTS8ebgV14v7cLdMOcOOyi2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1768967064322, 1779109665212);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('UUAkuLxFHDfIgi8Ne7ziP0buCQU2', '9dsRDwoLA2eTCQkLDCywhqqVKxl1', 'Davíð Roach Gunnarsson', NULL, 1773689302567, 1773689302567);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('UUAkuLxFHDfIgi8Ne7ziP0buCQU2', 'FXw3enl76NfhWTVliaW4lojwDam1', 'Gunnar Roach', NULL, 1773689304178, 1773689304178);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('UUAkuLxFHDfIgi8Ne7ziP0buCQU2', 'RVrF9x2WFbQfGcrfzBYhG0td7h22', 'Þóra Andrésdóttir', NULL, 1770226435293, 1776955091883);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('UUAkuLxFHDfIgi8Ne7ziP0buCQU2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1770225149426, 1778441250563);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('UdPT5z43AoNeIYuerj1yLu5HrQf2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1769104858140, 1769104858140);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('UlJLeEdIiUYtt79qDbHRmpWszkd2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1781540455920, 1781540455920);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('VCREsDNSvRcxQWKmHHkTNk9VcOu1', '049Wk4gbcuZJJ9MbCeN7GQuRYer2', 'gogo', NULL, 1782074972419, 1782074972419);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('VCREsDNSvRcxQWKmHHkTNk9VcOu1', 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2', 'kalli', NULL, 1781809442490, 1781809442490);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('VCREsDNSvRcxQWKmHHkTNk9VcOu1', 'GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2', 'No Name', NULL, 1779569740331, 1779934721790);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('VCREsDNSvRcxQWKmHHkTNk9VcOu1', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1776470979260, 1779935647240);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('VCREsDNSvRcxQWKmHHkTNk9VcOu1', 'wLFTAqKYsocZHS3BIhd4PyblaEf1', 'test_username_2', NULL, 1779624747180, 1779932379629);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('VtaPJJRr8nYkO0dcA2Op4UckE9F2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1780785620802, 1780785620802);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('dhJpbVtgazfdRuw89be3gmZ5y1I2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1775950492153, 1775950593541);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', '049Wk4gbcuZJJ9MbCeN7GQuRYer2', 'gogo', NULL, 1782074769531, 1782074769531);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', '09F1ryHgobTiwlfqF6Sf3ZdeMFp2', 'Muji', NULL, 1769256090451, 1771632482237);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', '8cqRApeZElMTXpGVTlZcOMq8Nfj1', 'Dj', NULL, 1767497288441, 1767497288441);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', '9dsRDwoLA2eTCQkLDCywhqqVKxl1', 'Davíð Roach', NULL, 1772865691991, 1779934857622);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'Avpry5LR0gebuh3tV1lQsGovYLl1', 'Hyo-sam', NULL, 1771619135961, 1778900236435);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2', 'kalli', NULL, 1779744858212, 1779942339440);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'FKLnfsnu2mdlb0yyGF5UJ5tisas2', 'Öggzz', NULL, 1775254587977, 1779467137596);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'FXw3enl76NfhWTVliaW4lojwDam1', 'Gunnar Roach', NULL, 1770387223983, 1779934794769);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'JzeKl0JyECePK1CDKOzFIdMEC2i1', 'Hafrún', NULL, 1774497756571, 1779934857810);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'KYM8gzxMu6MJvPkJaTC0hFh2cn52', 'Jázmin Bárdos', NULL, 1771625408821, 1780007188553);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'L0FDWn6KYHWmDqu8dyy1aLwvPHZ2', 'Smári R Gunnarsson', NULL, 1779747690649, 1779908491956);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'RVrF9x2WFbQfGcrfzBYhG0td7h22', 'Þóra Andrésdóttir', NULL, 1771859464921, 1779934857848);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'RZs9qkTS8ebgV14v7cLdMOcOOyi2', 'Hildur Sif Hilmarsdóttir', NULL, 1776190880568, 1779934857802);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2', 'Þorbjörg Roach', NULL, 1770225157357, 1779934857644);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'UdPT5z43AoNeIYuerj1yLu5HrQf2', 'Inga Ingólfsdóttir', NULL, 1769104857522, 1775662484341);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'UlJLeEdIiUYtt79qDbHRmpWszkd2', 'livanuj', NULL, 1781540456253, 1781540456253);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'VCREsDNSvRcxQWKmHHkTNk9VcOu1', 'Töggur Roach', NULL, 1776626579763, 1779939524374);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'VtaPJJRr8nYkO0dcA2Op4UckE9F2', 'MC Bjór', NULL, 1780785627564, 1780785627564);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'dhJpbVtgazfdRuw89be3gmZ5y1I2', 'Robert K.', NULL, 1775950492866, 1779934857614);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'mkc4IiI5LhSQH64gt1OvoncTYrt2', 'Sindri Austó !', NULL, 1773760646752, 1779934857821);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'nS4dmOOpWBNKNInxpbK4DmupjjA3', 'Bergur Thorgeirsson', NULL, 1780586316246, 1780586316246);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'ngB04ba21zbBpuwrbf3JbnmZ0Gr2', 'kiddi', NULL, 1779907939380, 1779938934728);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'o5ATY42g56N6pufEJRQ6UPy0Joy1', 'Páll Pampichler Pálsson', NULL, 1781308916855, 1781308916855);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'paZMw9G5RMdeClPCMGYrvMScIZk1', 'Aron Pabbi Klaka', NULL, 1769034578905, 1771655665057);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('iTAqv24EaybY6DB5DKG32zp5my42', 'we3njw1bnSNKs01j7g64NR90F7j2', 'Haukur', NULL, 1769018639647, 1779934411232);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('j0UhlxrSgVeWSIgNVsvrs6LgNP02', 'mkc4IiI5LhSQH64gt1OvoncTYrt2', 'Gudmundur', NULL, 1776237620009, 1776237620009);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('mkc4IiI5LhSQH64gt1OvoncTYrt2', 'Avpry5LR0gebuh3tV1lQsGovYLl1', 'Hyo-sam Nandkisore', NULL, 1774054555966, 1775972862363);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('mkc4IiI5LhSQH64gt1OvoncTYrt2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1773693237695, 1779502456380);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('mkc4IiI5LhSQH64gt1OvoncTYrt2', 'j0UhlxrSgVeWSIgNVsvrs6LgNP02', 'Vladka Gondza', NULL, 1776447589400, 1776447589400);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('nS4dmOOpWBNKNInxpbK4DmupjjA3', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1780586315934, 1780586315934);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('ngB04ba21zbBpuwrbf3JbnmZ0Gr2', 'iTAqv24EaybY6DB5DKG32zp5my42', '', NULL, 1782526001306, 1782526001306);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('o5ATY42g56N6pufEJRQ6UPy0Joy1', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kristinn Roach Gunnarsson', NULL, 1781308916261, 1781308916261);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('paZMw9G5RMdeClPCMGYrvMScIZk1', 'iTAqv24EaybY6DB5DKG32zp5my42', 'Kiddi', NULL, 1769034565616, 1769034565616);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('wLFTAqKYsocZHS3BIhd4PyblaEf1', 'GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2', 'test_username_1', NULL, 1779569575966, 1779569635598);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('wLFTAqKYsocZHS3BIhd4PyblaEf1', 'VCREsDNSvRcxQWKmHHkTNk9VcOu1', 'Töggur Roach', NULL, 1779624747399, 1779632383618);

INSERT OR IGNORE INTO contacts (owner_id, contact_id, nickname, conversation_id, saved_at, last_interaction_at)
VALUES ('we3njw1bnSNKs01j7g64NR90F7j2', 'iTAqv24EaybY6DB5DKG32zp5my42', 'iTAqv24EaybY6DB5DKG32zp5my42', NULL, 1769018637599, 1769018637599);

-- contacts: preserve canonical conversation_id (FK-guarded; NULL if conv row absent)
UPDATE contacts SET conversation_id = '77de5bb9-16d5-4dbe-94a1-4cb43cc9c629'
  WHERE owner_id = '049Wk4gbcuZJJ9MbCeN7GQuRYer2' AND contact_id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '77de5bb9-16d5-4dbe-94a1-4cb43cc9c629' AND dm_key = '049Wk4gbcuZJJ9MbCeN7GQuRYer2:VCREsDNSvRcxQWKmHHkTNk9VcOu1');

UPDATE contacts SET conversation_id = '1845702d-4be9-412f-beca-8ee8d4b82a3a'
  WHERE owner_id = '049Wk4gbcuZJJ9MbCeN7GQuRYer2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '1845702d-4be9-412f-beca-8ee8d4b82a3a' AND dm_key = '049Wk4gbcuZJJ9MbCeN7GQuRYer2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '1769ae7d-e2eb-4a16-85d7-3f1e5276e24e'
  WHERE owner_id = '09F1ryHgobTiwlfqF6Sf3ZdeMFp2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '1769ae7d-e2eb-4a16-85d7-3f1e5276e24e' AND dm_key = '09F1ryHgobTiwlfqF6Sf3ZdeMFp2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '187079f0-8853-4101-a554-826038e2c2aa'
  WHERE owner_id = '8cqRApeZElMTXpGVTlZcOMq8Nfj1' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '187079f0-8853-4101-a554-826038e2c2aa' AND dm_key = '8cqRApeZElMTXpGVTlZcOMq8Nfj1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '09a031ec-f3be-4f42-a10e-88b739ecba6e'
  WHERE owner_id = '9dsRDwoLA2eTCQkLDCywhqqVKxl1' AND contact_id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '09a031ec-f3be-4f42-a10e-88b739ecba6e' AND dm_key = '9dsRDwoLA2eTCQkLDCywhqqVKxl1:FXw3enl76NfhWTVliaW4lojwDam1');

UPDATE contacts SET conversation_id = '9d8f31c4-dcc9-4ecd-929e-784f7334d02b'
  WHERE owner_id = '9dsRDwoLA2eTCQkLDCywhqqVKxl1' AND contact_id = 'RVrF9x2WFbQfGcrfzBYhG0td7h22' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '9d8f31c4-dcc9-4ecd-929e-784f7334d02b' AND dm_key = '9dsRDwoLA2eTCQkLDCywhqqVKxl1:RVrF9x2WFbQfGcrfzBYhG0td7h22');

UPDATE contacts SET conversation_id = '82d11b0a-af96-43c5-9809-b2c7eb62c71a'
  WHERE owner_id = '9dsRDwoLA2eTCQkLDCywhqqVKxl1' AND contact_id = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '82d11b0a-af96-43c5-9809-b2c7eb62c71a' AND dm_key = '9dsRDwoLA2eTCQkLDCywhqqVKxl1:UUAkuLxFHDfIgi8Ne7ziP0buCQU2');

UPDATE contacts SET conversation_id = '22a3ffa9-cc52-4978-a840-571f01797138'
  WHERE owner_id = '9dsRDwoLA2eTCQkLDCywhqqVKxl1' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '22a3ffa9-cc52-4978-a840-571f01797138' AND dm_key = '9dsRDwoLA2eTCQkLDCywhqqVKxl1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = 'ee0138dd-8838-4622-a9d0-5efa1d858c61'
  WHERE owner_id = 'Avpry5LR0gebuh3tV1lQsGovYLl1' AND contact_id = 'KYM8gzxMu6MJvPkJaTC0hFh2cn52' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'ee0138dd-8838-4622-a9d0-5efa1d858c61' AND dm_key = 'Avpry5LR0gebuh3tV1lQsGovYLl1:KYM8gzxMu6MJvPkJaTC0hFh2cn52');

UPDATE contacts SET conversation_id = '7a63166a-c911-4b8e-bd59-bc8df3a1fe6f'
  WHERE owner_id = 'Avpry5LR0gebuh3tV1lQsGovYLl1' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '7a63166a-c911-4b8e-bd59-bc8df3a1fe6f' AND dm_key = 'Avpry5LR0gebuh3tV1lQsGovYLl1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '5607329b-b4a7-41dc-a0c9-3702783eb0a8'
  WHERE owner_id = 'Avpry5LR0gebuh3tV1lQsGovYLl1' AND contact_id = 'mkc4IiI5LhSQH64gt1OvoncTYrt2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '5607329b-b4a7-41dc-a0c9-3702783eb0a8' AND dm_key = 'Avpry5LR0gebuh3tV1lQsGovYLl1:mkc4IiI5LhSQH64gt1OvoncTYrt2');

UPDATE contacts SET conversation_id = '2c8ead8a-88b5-4af2-b66e-6f59631f11c2'
  WHERE owner_id = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2' AND contact_id = 'QKhccP7EjZOX3LHl6jXKxqyXK0m2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '2c8ead8a-88b5-4af2-b66e-6f59631f11c2' AND dm_key = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2:QKhccP7EjZOX3LHl6jXKxqyXK0m2');

UPDATE contacts SET conversation_id = '3e9b0de4-56d2-4afb-9177-c568464e8117'
  WHERE owner_id = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2' AND contact_id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '3e9b0de4-56d2-4afb-9177-c568464e8117' AND dm_key = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2:VCREsDNSvRcxQWKmHHkTNk9VcOu1');

UPDATE contacts SET conversation_id = '364f7581-a0c8-48da-b38f-1b5da1112a46'
  WHERE owner_id = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2' AND contact_id = 'XxlRUx60m3Na3lF7qKsvuPDrqBH2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '364f7581-a0c8-48da-b38f-1b5da1112a46' AND dm_key = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2:XxlRUx60m3Na3lF7qKsvuPDrqBH2');

UPDATE contacts SET conversation_id = '9df9b17e-cd6a-4803-9498-aa2e9ab9122b'
  WHERE owner_id = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '9df9b17e-cd6a-4803-9498-aa2e9ab9122b' AND dm_key = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '90709f81-ff2c-4d9d-b1e5-715cde0f2e1f'
  WHERE owner_id = 'FKLnfsnu2mdlb0yyGF5UJ5tisas2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '90709f81-ff2c-4d9d-b1e5-715cde0f2e1f' AND dm_key = 'FKLnfsnu2mdlb0yyGF5UJ5tisas2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '09a031ec-f3be-4f42-a10e-88b739ecba6e'
  WHERE owner_id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND contact_id = '9dsRDwoLA2eTCQkLDCywhqqVKxl1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '09a031ec-f3be-4f42-a10e-88b739ecba6e' AND dm_key = '9dsRDwoLA2eTCQkLDCywhqqVKxl1:FXw3enl76NfhWTVliaW4lojwDam1');

UPDATE contacts SET conversation_id = '3e045ad9-bbf0-48b5-a5db-d0b038f81c40'
  WHERE owner_id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND contact_id = 'L0FDWn6KYHWmDqu8dyy1aLwvPHZ2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '3e045ad9-bbf0-48b5-a5db-d0b038f81c40' AND dm_key = 'FXw3enl76NfhWTVliaW4lojwDam1:L0FDWn6KYHWmDqu8dyy1aLwvPHZ2');

UPDATE contacts SET conversation_id = '6ac12147-cda2-4732-9b8c-d9eff795a676'
  WHERE owner_id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND contact_id = 'RVrF9x2WFbQfGcrfzBYhG0td7h22' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '6ac12147-cda2-4732-9b8c-d9eff795a676' AND dm_key = 'FXw3enl76NfhWTVliaW4lojwDam1:RVrF9x2WFbQfGcrfzBYhG0td7h22');

UPDATE contacts SET conversation_id = '806fc1cc-3190-49ce-9ad5-24afcb164ba5'
  WHERE owner_id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND contact_id = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '806fc1cc-3190-49ce-9ad5-24afcb164ba5' AND dm_key = 'FXw3enl76NfhWTVliaW4lojwDam1:UUAkuLxFHDfIgi8Ne7ziP0buCQU2');

UPDATE contacts SET conversation_id = '27c9c7ea-277c-4ff1-b68b-3763b1c1c5e8'
  WHERE owner_id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '27c9c7ea-277c-4ff1-b68b-3763b1c1c5e8' AND dm_key = 'FXw3enl76NfhWTVliaW4lojwDam1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = 'e2d197ec-c206-4956-a129-35d9d9c2dc09'
  WHERE owner_id = 'GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2' AND contact_id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'e2d197ec-c206-4956-a129-35d9d9c2dc09' AND dm_key = 'GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2:VCREsDNSvRcxQWKmHHkTNk9VcOu1');

UPDATE contacts SET conversation_id = '9684d3c7-dc59-4c73-8899-45cad4a4d9db'
  WHERE owner_id = 'GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2' AND contact_id = 'wLFTAqKYsocZHS3BIhd4PyblaEf1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '9684d3c7-dc59-4c73-8899-45cad4a4d9db' AND dm_key = 'GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2:wLFTAqKYsocZHS3BIhd4PyblaEf1');

UPDATE contacts SET conversation_id = '9dbb7499-f0ad-4ad2-a1e3-48cd848bcc0a'
  WHERE owner_id = 'JzeKl0JyECePK1CDKOzFIdMEC2i1' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '9dbb7499-f0ad-4ad2-a1e3-48cd848bcc0a' AND dm_key = 'JzeKl0JyECePK1CDKOzFIdMEC2i1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = 'ee0138dd-8838-4622-a9d0-5efa1d858c61'
  WHERE owner_id = 'KYM8gzxMu6MJvPkJaTC0hFh2cn52' AND contact_id = 'Avpry5LR0gebuh3tV1lQsGovYLl1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'ee0138dd-8838-4622-a9d0-5efa1d858c61' AND dm_key = 'Avpry5LR0gebuh3tV1lQsGovYLl1:KYM8gzxMu6MJvPkJaTC0hFh2cn52');

UPDATE contacts SET conversation_id = '264eb2f3-5d3e-441e-8896-f84d25b22303'
  WHERE owner_id = 'KYM8gzxMu6MJvPkJaTC0hFh2cn52' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '264eb2f3-5d3e-441e-8896-f84d25b22303' AND dm_key = 'KYM8gzxMu6MJvPkJaTC0hFh2cn52:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '3e045ad9-bbf0-48b5-a5db-d0b038f81c40'
  WHERE owner_id = 'L0FDWn6KYHWmDqu8dyy1aLwvPHZ2' AND contact_id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '3e045ad9-bbf0-48b5-a5db-d0b038f81c40' AND dm_key = 'FXw3enl76NfhWTVliaW4lojwDam1:L0FDWn6KYHWmDqu8dyy1aLwvPHZ2');

UPDATE contacts SET conversation_id = '0b56dd9c-6409-4ff6-8112-90ce52f252ba'
  WHERE owner_id = 'L0FDWn6KYHWmDqu8dyy1aLwvPHZ2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '0b56dd9c-6409-4ff6-8112-90ce52f252ba' AND dm_key = 'L0FDWn6KYHWmDqu8dyy1aLwvPHZ2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '2c8ead8a-88b5-4af2-b66e-6f59631f11c2'
  WHERE owner_id = 'QKhccP7EjZOX3LHl6jXKxqyXK0m2' AND contact_id = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '2c8ead8a-88b5-4af2-b66e-6f59631f11c2' AND dm_key = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2:QKhccP7EjZOX3LHl6jXKxqyXK0m2');

UPDATE contacts SET conversation_id = '9d8f31c4-dcc9-4ecd-929e-784f7334d02b'
  WHERE owner_id = 'RVrF9x2WFbQfGcrfzBYhG0td7h22' AND contact_id = '9dsRDwoLA2eTCQkLDCywhqqVKxl1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '9d8f31c4-dcc9-4ecd-929e-784f7334d02b' AND dm_key = '9dsRDwoLA2eTCQkLDCywhqqVKxl1:RVrF9x2WFbQfGcrfzBYhG0td7h22');

UPDATE contacts SET conversation_id = '6ac12147-cda2-4732-9b8c-d9eff795a676'
  WHERE owner_id = 'RVrF9x2WFbQfGcrfzBYhG0td7h22' AND contact_id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '6ac12147-cda2-4732-9b8c-d9eff795a676' AND dm_key = 'FXw3enl76NfhWTVliaW4lojwDam1:RVrF9x2WFbQfGcrfzBYhG0td7h22');

UPDATE contacts SET conversation_id = '3e69692a-242d-4fb5-b656-154481dcc22a'
  WHERE owner_id = 'RVrF9x2WFbQfGcrfzBYhG0td7h22' AND contact_id = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '3e69692a-242d-4fb5-b656-154481dcc22a' AND dm_key = 'RVrF9x2WFbQfGcrfzBYhG0td7h22:UUAkuLxFHDfIgi8Ne7ziP0buCQU2');

UPDATE contacts SET conversation_id = '7e553a80-5e72-4411-9d1d-43569c8f19e7'
  WHERE owner_id = 'RVrF9x2WFbQfGcrfzBYhG0td7h22' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '7e553a80-5e72-4411-9d1d-43569c8f19e7' AND dm_key = 'RVrF9x2WFbQfGcrfzBYhG0td7h22:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = 'a282d67b-9a6a-4ff5-a397-ced7efc56f20'
  WHERE owner_id = 'RZs9qkTS8ebgV14v7cLdMOcOOyi2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'a282d67b-9a6a-4ff5-a397-ced7efc56f20' AND dm_key = 'RZs9qkTS8ebgV14v7cLdMOcOOyi2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '82d11b0a-af96-43c5-9809-b2c7eb62c71a'
  WHERE owner_id = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2' AND contact_id = '9dsRDwoLA2eTCQkLDCywhqqVKxl1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '82d11b0a-af96-43c5-9809-b2c7eb62c71a' AND dm_key = '9dsRDwoLA2eTCQkLDCywhqqVKxl1:UUAkuLxFHDfIgi8Ne7ziP0buCQU2');

UPDATE contacts SET conversation_id = '806fc1cc-3190-49ce-9ad5-24afcb164ba5'
  WHERE owner_id = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2' AND contact_id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '806fc1cc-3190-49ce-9ad5-24afcb164ba5' AND dm_key = 'FXw3enl76NfhWTVliaW4lojwDam1:UUAkuLxFHDfIgi8Ne7ziP0buCQU2');

UPDATE contacts SET conversation_id = '3e69692a-242d-4fb5-b656-154481dcc22a'
  WHERE owner_id = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2' AND contact_id = 'RVrF9x2WFbQfGcrfzBYhG0td7h22' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '3e69692a-242d-4fb5-b656-154481dcc22a' AND dm_key = 'RVrF9x2WFbQfGcrfzBYhG0td7h22:UUAkuLxFHDfIgi8Ne7ziP0buCQU2');

UPDATE contacts SET conversation_id = '4db347fb-e500-4ff7-83a0-3dc1c0e44752'
  WHERE owner_id = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '4db347fb-e500-4ff7-83a0-3dc1c0e44752' AND dm_key = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = 'ec586dc6-cd97-4596-ab2e-ad9549d06262'
  WHERE owner_id = 'UdPT5z43AoNeIYuerj1yLu5HrQf2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'ec586dc6-cd97-4596-ab2e-ad9549d06262' AND dm_key = 'UdPT5z43AoNeIYuerj1yLu5HrQf2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = 'a8616e80-c3e7-4487-98af-3f8d1f4fffcf'
  WHERE owner_id = 'UlJLeEdIiUYtt79qDbHRmpWszkd2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'a8616e80-c3e7-4487-98af-3f8d1f4fffcf' AND dm_key = 'UlJLeEdIiUYtt79qDbHRmpWszkd2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '77de5bb9-16d5-4dbe-94a1-4cb43cc9c629'
  WHERE owner_id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND contact_id = '049Wk4gbcuZJJ9MbCeN7GQuRYer2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '77de5bb9-16d5-4dbe-94a1-4cb43cc9c629' AND dm_key = '049Wk4gbcuZJJ9MbCeN7GQuRYer2:VCREsDNSvRcxQWKmHHkTNk9VcOu1');

UPDATE contacts SET conversation_id = '3e9b0de4-56d2-4afb-9177-c568464e8117'
  WHERE owner_id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND contact_id = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '3e9b0de4-56d2-4afb-9177-c568464e8117' AND dm_key = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2:VCREsDNSvRcxQWKmHHkTNk9VcOu1');

UPDATE contacts SET conversation_id = 'e2d197ec-c206-4956-a129-35d9d9c2dc09'
  WHERE owner_id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND contact_id = 'GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'e2d197ec-c206-4956-a129-35d9d9c2dc09' AND dm_key = 'GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2:VCREsDNSvRcxQWKmHHkTNk9VcOu1');

UPDATE contacts SET conversation_id = '0a58d751-d249-4a91-9c2f-ff2766764890'
  WHERE owner_id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '0a58d751-d249-4a91-9c2f-ff2766764890' AND dm_key = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '8bf9032e-6749-42be-ba9a-9830e77b99cf'
  WHERE owner_id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND contact_id = 'wLFTAqKYsocZHS3BIhd4PyblaEf1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '8bf9032e-6749-42be-ba9a-9830e77b99cf' AND dm_key = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1:wLFTAqKYsocZHS3BIhd4PyblaEf1');

UPDATE contacts SET conversation_id = '6651ef61-454e-4ce4-8b0a-3998ba9cf4ab'
  WHERE owner_id = 'VtaPJJRr8nYkO0dcA2Op4UckE9F2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '6651ef61-454e-4ce4-8b0a-3998ba9cf4ab' AND dm_key = 'VtaPJJRr8nYkO0dcA2Op4UckE9F2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '8365b42c-e60b-4565-8e6c-6bf8e84c5551'
  WHERE owner_id = 'dhJpbVtgazfdRuw89be3gmZ5y1I2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '8365b42c-e60b-4565-8e6c-6bf8e84c5551' AND dm_key = 'dhJpbVtgazfdRuw89be3gmZ5y1I2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '1845702d-4be9-412f-beca-8ee8d4b82a3a'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = '049Wk4gbcuZJJ9MbCeN7GQuRYer2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '1845702d-4be9-412f-beca-8ee8d4b82a3a' AND dm_key = '049Wk4gbcuZJJ9MbCeN7GQuRYer2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '1769ae7d-e2eb-4a16-85d7-3f1e5276e24e'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = '09F1ryHgobTiwlfqF6Sf3ZdeMFp2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '1769ae7d-e2eb-4a16-85d7-3f1e5276e24e' AND dm_key = '09F1ryHgobTiwlfqF6Sf3ZdeMFp2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '187079f0-8853-4101-a554-826038e2c2aa'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = '8cqRApeZElMTXpGVTlZcOMq8Nfj1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '187079f0-8853-4101-a554-826038e2c2aa' AND dm_key = '8cqRApeZElMTXpGVTlZcOMq8Nfj1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '22a3ffa9-cc52-4978-a840-571f01797138'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = '9dsRDwoLA2eTCQkLDCywhqqVKxl1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '22a3ffa9-cc52-4978-a840-571f01797138' AND dm_key = '9dsRDwoLA2eTCQkLDCywhqqVKxl1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '7a63166a-c911-4b8e-bd59-bc8df3a1fe6f'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'Avpry5LR0gebuh3tV1lQsGovYLl1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '7a63166a-c911-4b8e-bd59-bc8df3a1fe6f' AND dm_key = 'Avpry5LR0gebuh3tV1lQsGovYLl1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '9df9b17e-cd6a-4803-9498-aa2e9ab9122b'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '9df9b17e-cd6a-4803-9498-aa2e9ab9122b' AND dm_key = 'Cn5pDX2eyPSmktBdyYGZIy6v1uF2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '90709f81-ff2c-4d9d-b1e5-715cde0f2e1f'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'FKLnfsnu2mdlb0yyGF5UJ5tisas2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '90709f81-ff2c-4d9d-b1e5-715cde0f2e1f' AND dm_key = 'FKLnfsnu2mdlb0yyGF5UJ5tisas2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '27c9c7ea-277c-4ff1-b68b-3763b1c1c5e8'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '27c9c7ea-277c-4ff1-b68b-3763b1c1c5e8' AND dm_key = 'FXw3enl76NfhWTVliaW4lojwDam1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '9dbb7499-f0ad-4ad2-a1e3-48cd848bcc0a'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'JzeKl0JyECePK1CDKOzFIdMEC2i1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '9dbb7499-f0ad-4ad2-a1e3-48cd848bcc0a' AND dm_key = 'JzeKl0JyECePK1CDKOzFIdMEC2i1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '264eb2f3-5d3e-441e-8896-f84d25b22303'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'KYM8gzxMu6MJvPkJaTC0hFh2cn52' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '264eb2f3-5d3e-441e-8896-f84d25b22303' AND dm_key = 'KYM8gzxMu6MJvPkJaTC0hFh2cn52:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '0b56dd9c-6409-4ff6-8112-90ce52f252ba'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'L0FDWn6KYHWmDqu8dyy1aLwvPHZ2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '0b56dd9c-6409-4ff6-8112-90ce52f252ba' AND dm_key = 'L0FDWn6KYHWmDqu8dyy1aLwvPHZ2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '7e553a80-5e72-4411-9d1d-43569c8f19e7'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'RVrF9x2WFbQfGcrfzBYhG0td7h22' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '7e553a80-5e72-4411-9d1d-43569c8f19e7' AND dm_key = 'RVrF9x2WFbQfGcrfzBYhG0td7h22:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = 'a282d67b-9a6a-4ff5-a397-ced7efc56f20'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'RZs9qkTS8ebgV14v7cLdMOcOOyi2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'a282d67b-9a6a-4ff5-a397-ced7efc56f20' AND dm_key = 'RZs9qkTS8ebgV14v7cLdMOcOOyi2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '4db347fb-e500-4ff7-83a0-3dc1c0e44752'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '4db347fb-e500-4ff7-83a0-3dc1c0e44752' AND dm_key = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = 'ec586dc6-cd97-4596-ab2e-ad9549d06262'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'UdPT5z43AoNeIYuerj1yLu5HrQf2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'ec586dc6-cd97-4596-ab2e-ad9549d06262' AND dm_key = 'UdPT5z43AoNeIYuerj1yLu5HrQf2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = 'a8616e80-c3e7-4487-98af-3f8d1f4fffcf'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'UlJLeEdIiUYtt79qDbHRmpWszkd2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'a8616e80-c3e7-4487-98af-3f8d1f4fffcf' AND dm_key = 'UlJLeEdIiUYtt79qDbHRmpWszkd2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '0a58d751-d249-4a91-9c2f-ff2766764890'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '0a58d751-d249-4a91-9c2f-ff2766764890' AND dm_key = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '6651ef61-454e-4ce4-8b0a-3998ba9cf4ab'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'VtaPJJRr8nYkO0dcA2Op4UckE9F2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '6651ef61-454e-4ce4-8b0a-3998ba9cf4ab' AND dm_key = 'VtaPJJRr8nYkO0dcA2Op4UckE9F2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '8365b42c-e60b-4565-8e6c-6bf8e84c5551'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'dhJpbVtgazfdRuw89be3gmZ5y1I2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '8365b42c-e60b-4565-8e6c-6bf8e84c5551' AND dm_key = 'dhJpbVtgazfdRuw89be3gmZ5y1I2:iTAqv24EaybY6DB5DKG32zp5my42');

UPDATE contacts SET conversation_id = '7de0b1a0-7bdd-4e96-83a8-ca96362445b3'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'mkc4IiI5LhSQH64gt1OvoncTYrt2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '7de0b1a0-7bdd-4e96-83a8-ca96362445b3' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:mkc4IiI5LhSQH64gt1OvoncTYrt2');

UPDATE contacts SET conversation_id = '71dcc426-0210-4655-8acf-85e614b278d1'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'nS4dmOOpWBNKNInxpbK4DmupjjA3' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '71dcc426-0210-4655-8acf-85e614b278d1' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:nS4dmOOpWBNKNInxpbK4DmupjjA3');

UPDATE contacts SET conversation_id = 'a104eb10-0630-436f-acc4-524dff87d845'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'ngB04ba21zbBpuwrbf3JbnmZ0Gr2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'a104eb10-0630-436f-acc4-524dff87d845' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:ngB04ba21zbBpuwrbf3JbnmZ0Gr2');

UPDATE contacts SET conversation_id = '8de641fe-6f18-48e7-af61-999003faf344'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'o5ATY42g56N6pufEJRQ6UPy0Joy1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '8de641fe-6f18-48e7-af61-999003faf344' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:o5ATY42g56N6pufEJRQ6UPy0Joy1');

UPDATE contacts SET conversation_id = '3837c345-9b43-4e70-9953-eda6fb218e46'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'paZMw9G5RMdeClPCMGYrvMScIZk1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '3837c345-9b43-4e70-9953-eda6fb218e46' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:paZMw9G5RMdeClPCMGYrvMScIZk1');

UPDATE contacts SET conversation_id = '80d525eb-016e-4e8f-bd7e-354d3b49d5ca'
  WHERE owner_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND contact_id = 'we3njw1bnSNKs01j7g64NR90F7j2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '80d525eb-016e-4e8f-bd7e-354d3b49d5ca' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:we3njw1bnSNKs01j7g64NR90F7j2');

UPDATE contacts SET conversation_id = '18a1b29d-90f6-45ca-b41c-a393f02fede4'
  WHERE owner_id = 'j0UhlxrSgVeWSIgNVsvrs6LgNP02' AND contact_id = 'mkc4IiI5LhSQH64gt1OvoncTYrt2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '18a1b29d-90f6-45ca-b41c-a393f02fede4' AND dm_key = 'j0UhlxrSgVeWSIgNVsvrs6LgNP02:mkc4IiI5LhSQH64gt1OvoncTYrt2');

UPDATE contacts SET conversation_id = '5607329b-b4a7-41dc-a0c9-3702783eb0a8'
  WHERE owner_id = 'mkc4IiI5LhSQH64gt1OvoncTYrt2' AND contact_id = 'Avpry5LR0gebuh3tV1lQsGovYLl1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '5607329b-b4a7-41dc-a0c9-3702783eb0a8' AND dm_key = 'Avpry5LR0gebuh3tV1lQsGovYLl1:mkc4IiI5LhSQH64gt1OvoncTYrt2');

UPDATE contacts SET conversation_id = '7de0b1a0-7bdd-4e96-83a8-ca96362445b3'
  WHERE owner_id = 'mkc4IiI5LhSQH64gt1OvoncTYrt2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '7de0b1a0-7bdd-4e96-83a8-ca96362445b3' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:mkc4IiI5LhSQH64gt1OvoncTYrt2');

UPDATE contacts SET conversation_id = '18a1b29d-90f6-45ca-b41c-a393f02fede4'
  WHERE owner_id = 'mkc4IiI5LhSQH64gt1OvoncTYrt2' AND contact_id = 'j0UhlxrSgVeWSIgNVsvrs6LgNP02' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '18a1b29d-90f6-45ca-b41c-a393f02fede4' AND dm_key = 'j0UhlxrSgVeWSIgNVsvrs6LgNP02:mkc4IiI5LhSQH64gt1OvoncTYrt2');

UPDATE contacts SET conversation_id = '71dcc426-0210-4655-8acf-85e614b278d1'
  WHERE owner_id = 'nS4dmOOpWBNKNInxpbK4DmupjjA3' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '71dcc426-0210-4655-8acf-85e614b278d1' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:nS4dmOOpWBNKNInxpbK4DmupjjA3');

UPDATE contacts SET conversation_id = 'a104eb10-0630-436f-acc4-524dff87d845'
  WHERE owner_id = 'ngB04ba21zbBpuwrbf3JbnmZ0Gr2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = 'a104eb10-0630-436f-acc4-524dff87d845' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:ngB04ba21zbBpuwrbf3JbnmZ0Gr2');

UPDATE contacts SET conversation_id = '8de641fe-6f18-48e7-af61-999003faf344'
  WHERE owner_id = 'o5ATY42g56N6pufEJRQ6UPy0Joy1' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '8de641fe-6f18-48e7-af61-999003faf344' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:o5ATY42g56N6pufEJRQ6UPy0Joy1');

UPDATE contacts SET conversation_id = '3837c345-9b43-4e70-9953-eda6fb218e46'
  WHERE owner_id = 'paZMw9G5RMdeClPCMGYrvMScIZk1' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '3837c345-9b43-4e70-9953-eda6fb218e46' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:paZMw9G5RMdeClPCMGYrvMScIZk1');

UPDATE contacts SET conversation_id = '9684d3c7-dc59-4c73-8899-45cad4a4d9db'
  WHERE owner_id = 'wLFTAqKYsocZHS3BIhd4PyblaEf1' AND contact_id = 'GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '9684d3c7-dc59-4c73-8899-45cad4a4d9db' AND dm_key = 'GNSoX6Wb9ZdY6lr6DWRPBMoeZTg2:wLFTAqKYsocZHS3BIhd4PyblaEf1');

UPDATE contacts SET conversation_id = '8bf9032e-6749-42be-ba9a-9830e77b99cf'
  WHERE owner_id = 'wLFTAqKYsocZHS3BIhd4PyblaEf1' AND contact_id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '8bf9032e-6749-42be-ba9a-9830e77b99cf' AND dm_key = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1:wLFTAqKYsocZHS3BIhd4PyblaEf1');

UPDATE contacts SET conversation_id = '80d525eb-016e-4e8f-bd7e-354d3b49d5ca'
  WHERE owner_id = 'we3njw1bnSNKs01j7g64NR90F7j2' AND contact_id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND conversation_id IS NULL
    AND EXISTS (SELECT 1 FROM conversations WHERE id = '80d525eb-016e-4e8f-bd7e-354d3b49d5ca' AND dm_key = 'iTAqv24EaybY6DB5DKG32zp5my42:we3njw1bnSNKs01j7g64NR90F7j2');

-- users: email_hash from usersByEmail (powers email discovery)
UPDATE OR IGNORE users SET email_hash = 'YXJtZW5za2kyOEBnbWFpbC5jb20=' WHERE id = 'dhJpbVtgazfdRuw89be3gmZ5y1I2' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'YXJvbnNpZ3VyZ2VpcnNzb25AZ21haWwuY29t' WHERE id = 'paZMw9G5RMdeClPCMGYrvMScIZk1' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'YmVuamVubW9ybW9udC44MzY4NTZAZ21haWwuY29t' WHERE id = 'rC8YIKPrpGOkHjMrUJVlaKqcHSk1' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'YmVyZ3VydGhzc25AZ21haWwuY29t' WHERE id = 'nS4dmOOpWBNKNInxpbK4DmupjjA3' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'Z3NpbmRyaWhAZ21haWwuY29t' WHERE id = 'mkc4IiI5LhSQH64gt1OvoncTYrt2' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'Z3VubmFycm9hY2hAZ21haWwuY29t' WHERE id = 'FXw3enl76NfhWTVliaW4lojwDam1' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'ZGF2aWRyb2FjaGdAZ21haWwuY29t' WHERE id = '9dsRDwoLA2eTCQkLDCywhqqVKxl1' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'a3Jpc3Rpbm5yb2FjaEBnbWFpbC5jb20=' WHERE id = 'iTAqv24EaybY6DB5DKG32zp5my42' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'aGF1a3Vyc3ZAZ21haWwuY29t' WHERE id = 'we3njw1bnSNKs01j7g64NR90F7j2' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'aGFmcnVuMjBAZ21haWwuY29t' WHERE id = 'JzeKl0JyECePK1CDKOzFIdMEC2i1' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'aGlsZHVyaGlsbWFyc2RvdHRpcjIwQGdtYWlsLmNvbQ==' WHERE id = 'RZs9qkTS8ebgV14v7cLdMOcOOyi2' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'aHNuYW5ka2lzb3JlQGdtYWlsLmNvbQ==' WHERE id = 'Avpry5LR0gebuh3tV1lQsGovYLl1' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'aW5nYWljZUBnbWFpbC5jb20=' WHERE id = 'UdPT5z43AoNeIYuerj1yLu5HrQf2' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'amF6bWluYmFyZG9zMjAwM0BnbWFpbC5jb20=' WHERE id = 'KYM8gzxMu6MJvPkJaTC0hFh2cn52' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'bGFuZ2ludGVzQGdtYWlsLmNvbQ==' WHERE id = 'VtaPJJRr8nYkO0dcA2Op4UckE9F2' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'bmVndWxsOTlAZ21haWwuY29t' WHERE id = 'o5ATY42g56N6pufEJRQ6UPy0Joy1' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'c21hcmlyb2FjaGd1bm5hcnNzb25AZ21haWwuY29t' WHERE id = 'L0FDWn6KYHWmDqu8dyy1aLwvPHZ2' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'dG9nZ3Vycm9hY2hAZ21haWwuY29t' WHERE id = 'VCREsDNSvRcxQWKmHHkTNk9VcOu1' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'dGhvcmEuYW5kcmVzZG90dGlyQGdtYWlsLmNvbQ==' WHERE id = 'RVrF9x2WFbQfGcrfzBYhG0td7h22' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'dGhvcmJqb3JnLnJvYWNoQGdtYWlsLmNvbQ==' WHERE id = 'UUAkuLxFHDfIgi8Ne7ziP0buCQU2' AND email_hash IS NULL;

UPDATE OR IGNORE users SET email_hash = 'dmxhZGlzbGF2YXMua2FAZ21haWwuY29t' WHERE id = 'j0UhlxrSgVeWSIgNVsvrs6LgNP02' AND email_hash IS NULL;
