/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b02209631a253453954727c6110da530)
interface __BaseEnv_Env {
  FILES_BUCKET: R2Bucket;
  DB: D1Database;
  APP_ENV: 'production';
  FIREBASE_PROJECT_ID: 'vidu-aae11';
  R2_BUCKET_NAME: 'hangvidu-files';
  TURN_KEY_ID: 'ff936df931d23cb08b57351434e4fd9a';
  CONVERSATION_CHANNEL: DurableObjectNamespace<
    import('./src/index').ConversationChannel
  >;
  USER_MAILBOX: DurableObjectNamespace<import('./src/index').UserMailbox>;
  SIGNALING_ROOM: DurableObjectNamespace<import('./src/index').SignalingRoom>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
    durableNamespaces: 'ConversationChannel' | 'UserMailbox';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      'APP_ENV' | 'FIREBASE_PROJECT_ID' | 'R2_BUCKET_NAME' | 'TURN_KEY_ID'
    >
  > {}
}
